Repository kwizapp/nest-api, pull requests merged in 2020-03, with the labels that each got.

#2 Setup Devops Pipeline for Nest App
  .github/workflows/main.yml
  Dockerfile
  jest-e2e.json
  package.json
  src/app.module.ts
  src/generate-typings.ts
  src/graphql.ts
  src/main.ts
  src/movie/movie.e2e.spec.ts
  src/movie/movie.graphql
  src/movie/movie.service.spec.ts
  src/movie/movie.service.ts
  test/app.e2e-spec.ts
  test/jest-e2e.json
Labels: devops

#19 NestJS Upgrades
  package-lock.json
  package.json
Labels: dependencies

#32 #26: use dotenv to configure poster/metadata service location
  .env.template
  .gitignore
  README.md
  package-lock.json
  package.json
  src/main.ts
Labels: dependencies

#47 Movie query
  .env.template
  .github/workflows/main.yml
  README.md
  package.json
  src/app.module.ts
  src/main.ts
  src/movie/movie.e2e.spec.ts
  src/movie/movie.graphql
  src/movie/movie.resolver.ts
  src/movie/movie.service.spec.ts
  src/movie/movie.service.ts
  src/movie/movie.utils.ts
  src/movie/movies.ts
  test/movie/movie.e2e.spec.ts
  test/movie/movie.service.spec.ts
  test/movie/movie.utils.spec.ts
Labels: feature

#50 Calculate scores
  .sonarcloud.properties
  README.md
  src/app.module.ts
  src/movie/movie.module.ts
  src/score/score.graphql
  src/score/score.module.ts
  src/score/score.resolver.ts
  src/score/score.service.ts
  test/scores/score.e2e.spec.ts
  test/scores/score.service.spec.ts
Labels: feature
