Repository kwizapp/nest-api, pull requests merged in 2020-05, with the labels that each got.

#122 Fix: Deployment Conditionals
  .github/workflows/main.yml
Labels: bug, devops

#130 📝 Document code
  README.md
  src/app.module.ts
  src/main.ts
  src/movie/movie.module.ts
  src/movie/movie.resolver.ts
  src/movie/movie.service.ts
  src/movie/movie.utils.ts
  src/score/score.module.ts
  src/score/score.resolver.ts
  src/score/score.service.ts
Labels: documentation

#143 Separate production and staging environments
  .github/workflows/main.yml
Labels: devops

#148 Add release-drafter action
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: devops

#150 ⬆️ bump @kwizapp dependencies
  package-lock.json
  package.json
Labels: dependencies

#149 📝 Add description of repo structure to readme
  README.md
Labels: documentation
